trigger:
- master

pool:
  name: 'Local'

variables:
  # Storing the npm cache in the local workspace for better performance
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
# 1. Ensure the correct Node.js version is present
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

# 2. Look for existing cache based on your lockfile
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: 'Cache npm packages from previous runs'

# 3. Clean install of dependencies
# Using --cache ensures npm looks in our cached folder first
- script: |
    npm ci --cache $(npm_config_cache)
  displayName: 'Install Dependencies'

# 4. Run Coffee App Tests
- script: |
    npm run test
  displayName: 'Run Coffee App Cypress Test'