trigger:
- master

pool:
  name: 'Local'
  demands:
    - Agent.OS -equals Linux

variables:
  # Storing the npm cache in the local workspace for better performance
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
# 1. Ensure the correct Node.js version is present
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

# 2. Look for existing cache based on your lockfile
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: 'Cache npm packages from previous runs'

# 3. Clean install of dependencies
# Using --cache ensures npm looks in our cached folder first
- script: |
    npm ci --cache $(npm_config_cache)
  displayName: 'Install Dependencies'

# 4. Clean up old Test Reports
- script: |
    npm run cleanReport
  displayName: 'Clean Test Reports'

# 5. Run Coffee App Tests
- script: |
    npm run finalReport
  displayName: 'Run Coffee App Cypress Test'

# 6. Generate Mochawesome Report
- script: |
    npm run generateTestReport
  condition: always()
  displayName: 'Generate Test Report'

# 7. Publish Test Result as Pipeline Artifact
- task: PublishTestResults@2
  displayName: 'Upload JUnit Result'
  condition: always()
  inputs:
    testResultsFiles: 'cypress/results/test-results-*.xml'
    testRunTitle: 'Coffee App E2E Test Result'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    mergeTestResults: true
    publishRunAttachments: true
    failTaskOnFailedTests: true

- script: |
    echo "--- Current Directory Content ---"
    ls -R cypress/screenshots
  displayName: 'Verify Screenshot Physical Path'
  condition: always()

# 8. Publish Test Report as Pipeline Artifact
- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: 'Test_Report'
    artifact: 'TestReport'
    publishLocation: 'pipeline'
  displayName: 'Upload Test Report'

# 9. Publish Quick View Failure Screenshots
- task: PublishPipelineArtifact@1
  condition: failed()
  inputs:
    targetPath: 'cypress/screenshots'
    artifact: 'Failure_Screenshots'
  displayName: 'Publish Failure Screenshots'

# 10. Clean Up Test Report in Agent
- script: |
    echo "Cleaning up workspace..."
    rm -rf $(Pipeline.Workspace)/s/cypress/screenshots/*
    rm -rf $(Pipeline.Workspace)/s/cypress/videos/*
  condition: always()
  displayName: 'Cleanup Test Report'